version: "3.8"

services:
  postgres:
    container_name: inventory-db
    image: library/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: asu-inventory
    ports:
      - "5432:5432"
    restart: unless-stopped
