spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/asu-inventory
    username: postgres
    password: postgres
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/
server:
  port: 8081
